# Generated by Django 4.2.5 on 2023-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DataUpload',
        ),
    ]
